export const categories = [
  { id: 1, nombre: "Agroindustrias" },
  { id: 2, nombre: "Artesanía" },
  { id: 3, nombre: "Automotriz" },
  { id: 4, nombre: "Agricultura" },
  { id: 5, nombre: "Alimentos y bebidas" },
  { id: 6, nombre: "Acupunturistas" },
  { id: 7, nombre: "Agentes de Bolsa" },
  { id: 8, nombre: "Auditoría Médica" },
  { id: 9, nombre: "Asesoría Empresarial" },
  { id: 10, nombre: "Albañiles" },
  { id: 11, nombre: "Astrología y Tarot y Numerología" },
  { id: 12, nombre: "Atención al cliente" },
  { id: 13, nombre: "Aviación" },
  { id: 14, nombre: "Carpintería" },
  { id: 15, nombre: "Bazares" },
  { id: 16, nombre: "Bares" },
  { id: 17, nombre: "Bioingeniería" },
  { id: 18, nombre: "Boutiques" },
  { id: 19, nombre: "Casa y Hogar" },
  { id: 20, nombre: "Carnicerías y Verdulerías" },
  { id: 21, nombre: "Centros de Genética" },
  { id: 22, nombre: "Cabinas Internet" },
  { id: 23, nombre: "Catering" },
  { id: 24, nombre: "Comercio Electrónico" },
  { id: 25, nombre: "Colegios" },
  { id: 26, nombre: "Comercio Exterior" },
  { id: 27, nombre: "Comunicación" },
  { id: 28, nombre: "Cobranzas" },
  { id: 29, nombre: "Construcción e Inmobiliaria" },
  { id: 30, nombre: "Contabilidad y Finanzas" },
  { id: 31, nombre: "Cuero y calzado" },
  { id: 32, nombre: "Calígrafos" },
  { id: 33, nombre: "Capacitación para Atención de Mascotas" },
  { id: 34, nombre: "Chefs" },
  { id: 35, nombre: "Cines" },
  { id: 36, nombre: "Cocina y Repostería" },
  { id: 37, nombre: "Cocheras" },
  { id: 38, nombre: "Criadero de Animales Domésticos" },
  { id: 39, nombre: "Decoración" },
  { id: 40, nombre: "Disc Jockeys" },
  { id: 41, nombre: "Diseñadores de Sitios Web" },
  { id: 42, nombre: "Diseñadores Gráficos" },
  { id: 43, nombre: "Diversión y Esparcimiento" },
  { id: 44, nombre: "Droguería" },
  { id: 45, nombre: "Electricistas" },
  { id: 46, nombre: "Educación" },
  { id: 47, nombre: "Editoriales y Libros" },
  { id: 48, nombre: "Estudios Contables" },
  { id: 49, nombre: "Electrónica" },
  { id: 50, nombre: "Entretenimiento" },
  { id: 51, nombre: "Eventos y Servicios" },
  { id: 52, nombre: "Librería" },
  { id: 53, nombre: "Fotografía" },
  { id: 54, nombre: "Ferretería" },
  { id: 55, nombre: "Farmacias" },
  { id: 56, nombre: "Fabricación" },
  { id: 57, nombre: "Finanzas y Seguros" },
  { id: 58, nombre: "Gasfitería" },
  { id: 59, nombre: "Ganadería" },
  { id: 60, nombre: "Gastronomía" },
  { id: 61, nombre: "Hoteles" },
  { id: 62, nombre: "Hidrocarburos" },
  { id: 63, nombre: "Hardware" },
  { id: 64, nombre: "Industria Gráfica" },
  { id: 65, nombre: "Informática" },
  { id: 66, nombre: "Ingeniería" },
  { id: 67, nombre: "Insumos" },
  { id: 68, nombre: "Jardineros" },
  { id: 69, nombre: "Joyería" },
  { id: 70, nombre: "Limpieza" },
  { id: 71, nombre: "Lubricentros" },
  { id: 72, nombre: "Máquinas y Equipos" },
  { id: 73, nombre: "Medios de Comunicación" },
  { id: 74, nombre: "Muebles en General" },
  { id: 75, nombre: "Maestro Mayor de Obras" },
  { id: 76, nombre: "Magos" },
  { id: 77, nombre: "Mantenimientos" },
  { id: 78, nombre: "Mariachi" },
  { id: 79, nombre: "Masajistas y Masoterapeutas" },
  { id: 80, nombre: "Mensajerías" },
  { id: 81, nombre: "Mercados Mayoristas" },
  { id: 82, nombre: "Minería" },
  { id: 83, nombre: "Metalurgia" },
  { id: 84, nombre: "Modistas" },
  { id: 85, nombre: "Ortopedia" },
  { id: 86, nombre: "Plásticos y Empaques" },
  { id: 87, nombre: "Publicidad y Marketing" },
  { id: 88, nombre: "Payasos" },
  { id: 89, nombre: "Peluqueros" },
  { id: 90, nombre: "Pesca" },
  { id: 91, nombre: "Pintores" },
  { id: 92, nombre: "Plomeros" },
  { id: 93, nombre: "Podólogos" },
  { id: 94, nombre: "Profesionales de Deporte" },
  { id: 95, nombre: "Profesores" },
  { id: 96, nombre: "Pulidores de Pisos" },
  { id: 97, nombre: "Reparación de Artículos" },
  { id: 98, nombre: "Restaurantes" },
  { id: 99, nombre: "Servicios Sociales" },
  { id: 100, nombre: "Servicios Veterinarios" },
  { id: 101, nombre: "Salud y Vida" },
  { id: 102, nombre: "Salud y Belleza" },
  { id: 103, nombre: "Seguridad" },
  { id: 104, nombre: "Servicios Educativos" },
  { id: 105, nombre: "Servicios de Internet" },
  { id: 106, nombre: "Servicios Profesionales y Consultoría" },
  { id: 107, nombre: "Software" },
  { id: 108, nombre: "Tiendas" },
  { id: 109, nombre: "Tecnología/Telecomunicaciones" },
  { id: 110, nombre: "Textiles" },
  { id: 111, nombre: "Transporte" },
  { id: 112, nombre: "Transporte Aéreo" },
  { id: 113, nombre: "Turismo" },
  { id: 114, nombre: "Telecomunicaciones" },
  { id: 115, nombre: "Universidad" },
  { id: 116, nombre: "Vehículos" },
  { id: 117, nombre: "Vigilancia" },
  { id: 118, nombre: "Otro Rubro" },
];
