export const categories = [
  { id: 1, value: "Agroindustrias" },
  { id: 2, value: "Artesanía" },
  { id: 3, value: "Automotriz" },
  { id: 4, value: "Agricultura" },
  { id: 5, value: "Alimentos y bebidas" },
  { id: 6, value: "Acupunturistas" },
  { id: 7, value: "Agentes de Bolsa" },
  { id: 8, value: "Auditoría Médica" },
  { id: 9, value: "Asesoría Empresarial" },
  { id: 10, value: "Albañiles" },
  { id: 11, value: "Astrología y Tarot y Numerología" },
  { id: 12, value: "Atención al cliente" },
  { id: 13, value: "Aviación" },
  { id: 14, value: "Carpintería" },
  { id: 15, value: "Bazares" },
  { id: 16, value: "Bares" },
  { id: 17, value: "Bioingeniería" },
  { id: 18, value: "Boutiques" },
  { id: 19, value: "Casa y Hogar" },
  { id: 20, value: "Carnicerías y Verdulerías" },
  { id: 21, value: "Centros de Genética" },
  { id: 22, value: "Cabinas Internet" },
  { id: 23, value: "Catering" },
  { id: 24, value: "Comercio Electrónico" },
  { id: 25, value: "Colegios" },
  { id: 26, value: "Comercio Exterior" },
  { id: 27, value: "Comunicación" },
  { id: 28, value: "Cobranzas" },
  { id: 29, value: "Construcción e Inmobiliaria" },
  { id: 30, value: "Contabilidad y Finanzas" },
  { id: 31, value: "Cuero y calzado" },
  { id: 32, value: "Calígrafos" },
  { id: 33, value: "Capacitación para Atención de Mascotas" },
  { id: 34, value: "Chefs" },
  { id: 35, value: "Cines" },
  { id: 36, value: "Cocina y Repostería" },
  { id: 37, value: "Cocheras" },
  { id: 38, value: "Criadero de Animales Domésticos" },
  { id: 39, value: "Decoración" },
  { id: 40, value: "Disc Jockeys" },
  { id: 41, value: "Diseñadores de Sitios Web" },
  { id: 42, value: "Diseñadores Gráficos" },
  { id: 43, value: "Diversión y Esparcimiento" },
  { id: 44, value: "Droguería" },
  { id: 45, value: "Electricistas" },
  { id: 46, value: "Educación" },
  { id: 47, value: "Editoriales y Libros" },
  { id: 48, value: "Estudios Contables" },
  { id: 49, value: "Electrónica" },
  { id: 50, value: "Entretenimiento" },
  { id: 51, value: "Eventos y Servicios" },
  { id: 52, value: "Librería" },
  { id: 53, value: "Fotografía" },
  { id: 54, value: "Ferretería" },
  { id: 55, value: "Farmacias" },
  { id: 56, value: "Fabricación" },
  { id: 57, value: "Finanzas y Seguros" },
  { id: 58, value: "Gasfitería" },
  { id: 59, value: "Ganadería" },
  { id: 60, value: "Gastronomía" },
  { id: 61, value: "Hoteles" },
  { id: 62, value: "Hidrocarburos" },
  { id: 63, value: "Hardware" },
  { id: 64, value: "Industria Gráfica" },
  { id: 65, value: "Informática" },
  { id: 66, value: "Ingeniería" },
  { id: 67, value: "Insumos" },
  { id: 68, value: "Jardineros" },
  { id: 69, value: "Joyería" },
  { id: 70, value: "Limpieza" },
  { id: 71, value: "Lubricentros" },
  { id: 72, value: "Máquinas y Equipos" },
  { id: 73, value: "Medios de Comunicación" },
  { id: 74, value: "Muebles en General" },
  { id: 75, value: "Maestro Mayor de Obras" },
  { id: 76, value: "Magos" },
  { id: 77, value: "Mantenimientos" },
  { id: 78, value: "Mariachi" },
  { id: 79, value: "Masajistas y Masoterapeutas" },
  { id: 80, value: "Mensajerías" },
  { id: 81, value: "Mercados Mayoristas" },
  { id: 82, value: "Minería" },
  { id: 83, value: "Metalurgia" },
  { id: 84, value: "Modistas" },
  { id: 85, value: "Ortopedia" },
  { id: 86, value: "Plásticos y Empaques" },
  { id: 87, value: "Publicidad y Marketing" },
  { id: 88, value: "Payasos" },
  { id: 89, value: "Peluqueros" },
  { id: 90, value: "Pesca" },
  { id: 91, value: "Pintores" },
  { id: 92, value: "Plomeros" },
  { id: 93, value: "Podólogos" },
  { id: 94, value: "Profesionales de Deporte" },
  { id: 95, value: "Profesores" },
  { id: 96, value: "Pulidores de Pisos" },
  { id: 97, value: "Reparación de Artículos" },
  { id: 98, value: "Restaurantes" },
  { id: 99, value: "Servicios Sociales" },
  { id: 100, value: "Servicios Veterinarios" },
  { id: 101, value: "Salud y Vida" },
  { id: 102, value: "Salud y Belleza" },
  { id: 103, value: "Seguridad" },
  { id: 104, value: "Servicios Educativos" },
  { id: 105, value: "Servicios de Internet" },
  { id: 106, value: "Servicios Profesionales y Consultoría" },
  { id: 107, value: "Software" },
  { id: 108, value: "Tiendas" },
  { id: 109, value: "Tecnología/Telecomunicaciones" },
  { id: 110, value: "Textiles" },
  { id: 111, value: "Transporte" },
  { id: 112, value: "Transporte Aéreo" },
  { id: 113, value: "Turismo" },
  { id: 114, value: "Telecomunicaciones" },
  { id: 115, value: "Universidad" },
  { id: 116, value: "Vehículos" },
  { id: 117, value: "Vigilancia" },
  { id: 118, value: "Otro Rubro" },
];
