// Countries.ts
export const countries = [
  {
    country: "Perú",
    id: "01",
    alias: "PER",
    cities: [
      { id: "01", city: "Amazonas", alias: "AMA" },
      { id: "02", city: "Áncash", alias: "ANC" },
      { id: "03", city: "Apurímac", alias: "APU" },
      { id: "04", city: "Arequipa", alias: "AQP" },
      { id: "05", city: "Ayacucho", alias: "AYC" },
      { id: "06", city: "Cajamarca", alias: "CAJ" },
      { id: "07", city: "Callao", alias: "CAL" },
      { id: "08", city: "Cusco", alias: "CUS" },
      { id: "09", city: "Huancavelica", alias: "HUV" },
      { id: "10", city: "Huánuco", alias: "HUC" },
      { id: "11", city: "Ica", alias: "ICA" },
      { id: "12", city: "Junín", alias: "JUN" },
      { id: "13", city: "La Libertad", alias: "LIB" },
      { id: "14", city: "Lambayeque", alias: "LAM" },
      { id: "15", city: "Lima", alias: "LIM" },
      { id: "16", city: "Loreto", alias: "LOR" },
      { id: "17", city: "Madre de Dios", alias: "MDD" },
      { id: "18", city: "Moquegua", alias: "MOQ" },
      { id: "19", city: "Pasco", alias: "PAS" },
      { id: "20", city: "Piura", alias: "PIU" },
      { id: "21", city: "Puno", alias: "PUN" },
      { id: "22", city: "San Martín", alias: "SAN" },
      { id: "23", city: "Tacna", alias: "TAC" },
      { id: "24", city: "Tumbes", alias: "TUM" },
      { id: "25", city: "Ucayali", alias: "UCA" },
    ],
  },
];
