// Countries.ts
export const countries = [
  {
    value: "Perú",
    id: "01",
    alias: "PER",
    cities: [
      { id: "01", value: "Amazonas", alias: "AMA" },
      { id: "02", value: "Áncash", alias: "ANC" },
      { id: "03", value: "Apurímac", alias: "APU" },
      { id: "04", value: "Arequipa", alias: "AQP" },
      { id: "05", value: "Ayacucho", alias: "AYC" },
      { id: "06", value: "Cajamarca", alias: "CAJ" },
      { id: "07", value: "Callao", alias: "CAL" },
      { id: "08", value: "Cusco", alias: "CUS" },
      { id: "09", value: "Huancavelica", alias: "HUV" },
      { id: "10", value: "Huánuco", alias: "HUC" },
      { id: "11", value: "Ica", alias: "ICA" },
      { id: "12", value: "Junín", alias: "JUN" },
      { id: "13", value: "La Libertad", alias: "LIB" },
      { id: "14", value: "Lambayeque", alias: "LAM" },
      { id: "15", value: "Lima", alias: "LIM" },
      { id: "16", value: "Loreto", alias: "LOR" },
      { id: "17", value: "Madre de Dios", alias: "MDD" },
      { id: "18", value: "Moquegua", alias: "MOQ" },
      { id: "19", value: "Pasco", alias: "PAS" },
      { id: "20", value: "Piura", alias: "PIU" },
      { id: "21", value: "Puno", alias: "PUN" },
      { id: "22", value: "San Martín", alias: "SAN" },
      { id: "23", value: "Tacna", alias: "TAC" },
      { id: "24", value: "Tumbes", alias: "TUM" },
      { id: "25", value: "Ucayali", alias: "UCA" },
    ],
  },
];
