export const notificationSystemSenderId = "1";
export const notificationSystemSenderName = "TCompra";
export const broadcastNotificationExpiresIn = 45; // minutos
export const directNotificationExpiresIn = 30; //  días
export const subUserRoomName = "subUser";
export const userRoomName = "roomLogin";
export const accessTokenExpiresIn = "2m";
export const refreshTokenExpiresIn = "10m";
export const alternativeAccessTokenExpiresIn = 3600;
