export const notificationSystemSenderId = "1";
export const notificationSystemSenderName = "TCompra";
export const broadcastNotificationExpiresIn = 45; // minutos
export const directNotificationExpiresIn = 30; //  días
export const subUserRoomName = "subUser";
export const userRoomName = "roomLogin";
export const accessTokenExpiresIn = "1m"; //"2h";
export const refreshTokenExpiresIn = "2m"; //"7d";
export const alternativeAccessTokenExpiresIn = 3600;
